version: '3.18'

services:
    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: dev
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - data:/data/db
        ports:
            - '27017:27017'
    server:
        env_file: .env
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3001:3001
        volumes:
            - /app/node_modules
            - ./:/app
        depends_on:
            - mongodb
volumes:
    data:
