const errorTypes = {
  CREDENTIALS_INVALID: "CREDENTIALS_INVALID",
  SERVER_ERROR: "SERVER_ERROR",
  USER_EXISTS: "USER_EXISTS",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
};

export default errorTypes;
